output_folder: "C:\\temp"
org_id: "8aa3fe01-4533-4d8a-bebe-fb9c95015380"
report_start_from: 1
yango_start_from: 30
threads: 5
delay: 0
reports:
  - REPORT_TYPE_PAYMENTS_ORDER
  - REPORT_TYPE_PAYMENTS_ORGANIZATION
