name: Build Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .\requirements.txt

      - name: Build executable
        run: pyinstaller --onefile download_report_careem.py

      - name: List contents of dist folder
        run: dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/download_report_careem.exe

      - name: Build executable
        run: pyinstaller --onefile download_report_yango.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/download_report_yango.exe
